### ISSUE TITLE
How to compile the injector

### ISSUE THREAD

**Issue by Titaniumtown** [blefeuvr/diep-rl#3]
Don't you have to compile the xpi file extension for firefox when you change the js? If so, how? (I'm on linux) Correct me if I'm wrong, I want to make sure I don't make an error when I make a pull request.

**Comment by blefeuvr** [comment]
Yes, you can run `diep-rl/diep_injector/zipper.sh` to "compile" the xpi extension.
```bash
bash zipper.sh
```
